### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by dnbh** [wichtounet/etl#1]
Out of curiosity, have you compared performance between ETL and something like Eigen or Blaze? I know at least Eigen can link against BLAS as well.

I'm looking for a matrix library to use and came across yours.

Thanks!

**Comment by wichtounet** [comment]
Hi, 

I've a benchmark against Blaze and Eigen: https://github.com/wichtounet/etl_vs_blaze. 
Unfortunately, I haven't yet published the results online, but you can run it yourself if you have have blaze and Eigen installed. 

Generally, ETL is faster or as fast as Eigen. And on most cases,  it is on par with Blaze. However, Blaze is generally the fastest framework for now. Moreover, both frameworks have more features than ETL right now. 

I would advise you to try Blaze or ETL rather than Eigen. 

Baptiste

**Comment by wichtounet** [comment]
I'm considering this issue closed. Don't hesitate to post to reopen it to if you don't think it's the case.

**Comment by dnbh** [comment]
Thank you for your response! I'm sorry for not reporting earlier that that was a satisfactory help.
